output_dir: ~/scratch/logicnn_output/

dataset:
  class: CoDEx
  path: ~/kg-datasets/
  size: m

task:
  class: KnowledgeGraphCompletion
  model:
    class: BackwardForwardReasoning
    backward_model:
      class: RuleNBFNet
      input_dim: 64
      num_hop: 2
      message_func: distmult
      aggregate_func: sum
      short_cut: yes
      layer_norm: yes
      dependent: yes
      transformer_combine: yes
    forward_model:
      class: NBFNet
      input_dim: 64
      hidden_dims: [64, 64, 64]
      message_func: distmult
      aggregate_func: sum
      short_cut: yes
      layer_norm: yes
      dependent: yes
      transformer_combine: yes
    remove_one_hop: yes
    query_as_indicator: yes
  criterion: bce
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 0.5
  sample_weight: no

optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 64

train:
  num_epoch: 10